---
# tasks file for myapp_infra
- name: create launch config
  ec2_lc:
    name: "{{ app_name }}"
    image_id: "{{ ami }}"
    key_name: ""
    region: "{{ region }}"
    security_groups: "{{ tower_callback_client_group_id }},{{ tower_client_group_id }}"
    instance_type: "{{ instance_size }}"
    user_data: "{{ user_data }}"
  tags: launch_config
