---
# tasks file for Infra
- name: Create Instance (Debian 8 HVM)
      ec2: image={{ image }}
           instance_type={{ instance_type }}
           keypair={{ keypair }}
           instance_tags='{"Name":"{{ inst_name }}","Environment":"{{ serv_env }}","Class":"{{ serv_class}}","Provision":"{{ provisionby }}"}'
           region={{ region }}
           group="{{ tower_callback_client_group_id }},{{ tower_client_group_id }}"
           user_data: "{{ user_data }}"
           wait=true
           wait_timeout: 600
           tags: create_instance
           register: ec2_info
